
source 'https://rubygems.org'

gem 'sinatra-assetpack'
gem 'sinatra-support'

gem 'rappgem', path: "../../"

group :development, :test do
  gem 'rspec-given'
  gem "capybara"
  gem "capybara-webkit"
end
